version: 2
snapshot:
  percy-css: |
    #toast,
    #team-ux-in-2024-disclaimer { 
      display: none; 
    }
    
    .project-image-link img {
      opacity: 1 !important;
    }
discovery:
  allowedHostnames: []
  disallowedHostnames: []
  networkIdleTimeout: 100
  captureMockedServiceWorker: false
upload:
  files: "**/*.{png,jpg,jpeg}"
  ignore: ""
  stripExtensions: false
