name: Deploy to Infomaniak

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      # to fix: https://vercel.com/guides/corepack-errors-github-actions
      # should be temporary.
      - name: Install corepack
        shell: "bash"
        run: npm install -g corepack@latest

      - name: Setup PNPM using corepack
        shell: "bash"
        run: |
          corepack enable
          corepack install

      - name: Install
        shell: "bash"
        run: pnpm i

      - name: Build
        shell: "bash"
        run: pnpm build

      - name: Deploy to Infomaniak
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          SOURCE: "dist/"
          TARGET: ${{ secrets.REMOTE_TARGET }}
          ARGS: "-rlgoDzvc -i --delete"
