name: Run visual testing

on:
  pull_request:
    # run visual diffing test if label is added, and for all subsequent pushed commits
    types: [ labeled, opened, synchronize, reopened ]

jobs:
  build:
    if: ${{ github.event.label.name == 'visual-testing' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build team-ux.com with Astro
        uses: withastro/action@v2
        with:
          package-manager: pnpm@8
      - name: Take team-ux.com screenshots and upload them to Percy
        run: pnpm percy snapshot dist/
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
