name: Run visual testing

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  visual-testing:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'visual-testing') }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build team-ux.com with Astro
        uses: withastro/action@v3
        with:
          package-manager: pnpm@9.9.0
      - name: Take team-ux.com screenshots and upload them to Percy
        run: pnpm percy snapshot dist/
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
